name: Update

on:
  schedule:
    - cron: "0/15 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tools/version-checker

    steps:
      - uses: actions/checkout@v2

      - name: Install node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Allow script execution
        run: chmod +x ./update-version

      - name: Run Updater
        run: ./update-version

      - name: Store WA Version
        run: echo WA_VERSION=`cat ./version` >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: auto-wa-web-update/patch
          delete-branch: true
